### ISSUE TITLE
Authentification

### ISSUE THREAD

**Issue by giga-development** [GrahamCampbell/Laravel-Parse#10]
Have you been able to build registration, login etc? I wanted to use the classes that are already there and just change a few thing to parse, but it has unfolded to be much more complicated and I can't find any diocumentation online. I was able to sign up a user, although it gives me an error saying I can't sign up a user with an empty password. It did create the user though. Unfortunately I was not able to change the login. It looks like it´s really hard to change all this stuff to parse. how did you do it?

**Comment by GrahamCampbell** [comment]
Unfortunately, I can't really offer any support. I don't even use Parse. Sorry.
