### ISSUE TITLE
Parse 1.2.1 require the mountPath

### ISSUE THREAD

**Issue by kainxspirits** [GrahamCampbell/Laravel-Parse#17]
The latest version of the parse php sdk introduced some new changes. It seems there is an issue with the initialization of ParseClient because they now ask the mount path as second argument.
https://github.com/ParsePlatform/parse-php-sdk/blob/master/src/Parse/ParseClient.php#L148

**Comment by GrahamCampbell** [comment]
Sigh. Why did that have to make a breaking change in a patch release. :/

**Comment by GrahamCampbell** [comment]
Are you able to send a PR here please?

**Comment by kainxspirits** [comment]
Yes sure. Not right now, but I can do that during the weekend.

**Comment by kainxspirits** [comment]
Actually, i'm not sure which method we should adopt to fix this issue. 

We can either, add a new configuration option for the mount path (but that would also be a breaking change). Or we can parse the server url and split the hostname and the mount path ( I don't like this approach, but at least it would not require any changes for those updating the lib).

**Comment by shalomabitan** [comment]
Hi,

I made a pull request with what I think is an appropriate way of correcting the discrepancies #18 

Thanks

**Comment by GrahamCampbell** [comment]
This will be fixed in the next release.
