### ISSUE TITLE
This Laravel Parse Integration is working with Laravel 5.3 and Parse Platform Server

### ISSUE THREAD

**Issue by sanjibnarzary** [GrahamCampbell/Laravel-Parse#20]
Recently I tried to connect my Parse server with LaraParse because in my project I used Laravel as a main framework and I needed to connect the Parse server from my laravel code. I was helpless and tried with LaraParse but it did not help. I tried with the official only PHP parse-sdk It still did not help me with laravel and parse connection, but it was working fine from the outside framework.

Today I have tested with this Laravel-Parse along with the official PHP/parse-sdk and it was working fine, it also works with the latest Laravel 5.3.* . So I would like to thank you for making this driver.

**Comment by GrahamCampbell** [comment]
:)
