### ISSUE TITLE
graham-campbell/parse could not be found

### ISSUE THREAD

**Issue by nam-co** [GrahamCampbell/Laravel-Parse#4]
Hi Graham, once again thank you for your contributions, this package has really help me, I just uploaded to L5 and when I put ("graham-campbell/parse": "~2.0") in the composer and I get this error:
"The requested package graham-campbell/parse could not be found in any version, there may be a typo in the package name."

I wonder what Im doing wrong?

Appreciate any help, regards

**Comment by GrahamCampbell** [comment]
You need to use `~2.0@dev` for now. I plan to tag the v2.0.0 release later today.
