### ISSUE TITLE
Does this work with Laravel 4?

### ISSUE THREAD

**Issue by Hesesses** [GrahamCampbell/Laravel-Parse#7]

**Comment by GrahamCampbell** [comment]
Yes, 1.x will.

**Comment by GrahamCampbell** [comment]
Please read https://github.com/GrahamCampbell/Laravel-Parse/releases.

**Comment by Hesesses** [comment]
Thank you!

**Comment by GrahamCampbell** [comment]
I'd recommend upgrading to L5.1 asap though. It's also an LTS release, so you won't need to upgrade again for 2 years.
