### ISSUE TITLE
Lumen support

### ISSUE THREAD

**Issue by whitefoxy** [GrahamCampbell/Laravel-Parse#8]
Please add to this package Lumen support. It works on lumen, but there are troubles with config loading. It don't load config from correct path.

**Comment by GrahamCampbell** [comment]
Lumen should work fine if you follow lumen's docs.

**Comment by whitefoxy** [comment]
I followed the instructions and did everything right.
Config file is in the folder "config". Path "config / parse.php".

In your code there are:
```
protected function setupParse(Application $app)
    {
        $config = $app->config->get('parse');
        ParseClient::initialize($config['app_id'], $config['rest_key'], $config['master_key']);
    }
```

But in Lumen ```$app->config->get('parse')``` will return ```null```.
There must be something like this:
```
protected function setupParse(Application $app)
    {
        $app->configure('parse');
        ParseClient::initialize(config('parse.app_id'), config('parse.rest_key'), config('parse.master_key');
    }
```

Check the Lumen documentation please. With my code all work fine, but I don't know how it will be in Laravel.

**Comment by GrahamCampbell** [comment]
No, you don't need to do that.

**Comment by GrahamCampbell** [comment]
You NEED to call `$app->configure('parse');` yourself, then the original code will work just fine.

**Comment by GrahamCampbell** [comment]
You need to do this when you register the service provider, as documented.

**Comment by GrahamCampbell** [comment]
`config('parse.app_id')` would definitely be wrong. That doesn't need to change.

**Comment by GrahamCampbell** [comment]
Meh, I might as well call configure then in all my packages.

**Comment by GrahamCampbell** [comment]
I'll get that done now.

**Comment by GrahamCampbell** [comment]
Does `~2.3@dev` work for you now?

**Comment by whitefoxy** [comment]
Yes, it works! Thank you!

**Comment by GrahamCampbell** [comment]
Great. :)
